version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  wordpress1:
    image: wordpress:latest
    platform: linux/arm64
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
      - backend

  wordpress2:
    image: wordpress:latest
    platform: linux/arm64
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
      - backend

  wordpress3:
    image: wordpress:latest
    platform: linux/arm64
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
      - backend

  nginx:
    image: nginx:latest
    platform: linux/arm64
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - wordpress_data:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - frontend

  locust:
    image: grubykarol/locust
    environment:
      - ATTACKED_HOST=http://nginx:80
      - LOCUST_FILE=/mnt/locust/locustfile.py
    volumes:
      - ./locust:/mnt/locust
    ports:
      - "8089:8089"
    networks:
      - frontend

volumes:
  wordpress_data:
  mysql_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

